NAME: 'SBOM Generation and Scanning'
description: 'Generate a software vill of materials and scans for knwow vulnerabilities'
author: 'jose'
outputs:
  sbom-file:
  description: 'the syft genereated sbom'
  value: ${{ steps.sbom-gen-and-scane.outputs.sbom-file }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  
